# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        default:
            alias: 'GuzzleHttp\ClientInterface'
            config:
                headers:
                    user-agent: 'bbc.co.uk-programmes/%cosmos_component_release% (%cosmos_environment%)'
                cert: '/etc/pki/dev.bbc.co.uk.pem'
                ssl_key: '/etc/pki/dev.bbc.co.uk.pem'
                verify: false
                timeout: 60
                connect_timeout: 10
                force_ip_resolve: 'v4'
