# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    # These are the default feed environments for LIVE. They may be overridden
    # on a per cosmos environment basis by editing services_prod_int.yml or
    # services_prod_test.yml
    app.feed_env.orbit: 'live'
    app.feed_env.branding: 'live'
    app.feed_env.morph.lxpromo: 'live'
    app.feed_env.morph.riddle: 'live'
    aws_s3_region: eu-west-1

    app.default_locale: 'en_GB'
    app.orbit_client.class: BBC\BrandingClient\OrbitClient
    app.branding_client.class: BBC\BrandingClient\BrandingClient
    app.morph_client.class: BBC\ProgrammesMorphLibrary\MorphClient
    app.metric_cache.class: App\Metrics\Cache\MetricCacheApcu
    app.metric_backend.class: App\Metrics\Backend\CloudWatchMetricBackend
    frontend.aws.http_timeout: 15
    frontend.aws.http_connect_timeout: 5

    # External Apis
    app.ada.baseurl: 'https://ada.api.bbci.co.uk'
    app.ada.class_service.class: App\ExternalApi\Ada\Service\AdaClassService
    app.ada.programme_service.class: App\ExternalApi\Ada\Service\AdaProgrammeService
    app.electron.baseurl: 'https://api.live.bbc.co.uk/electron'
    app.electron.service.class: App\ExternalApi\Electron\Service\ElectronService
    app.idtquiz.service.class: App\ExternalApi\IdtQuiz\Service\IdtQuizService
    app.isite.baseurl: 'https://api.live.bbc.co.uk/isite2-content-reader'
    app.isite.article_service.class: App\ExternalApi\Isite\Service\ArticleService
    app.isite.profile_service.class: App\ExternalApi\Isite\Service\ProfileService
    app.recipes.baseurl: 'https://food-api-proxy.tools.bbc.co.uk/recipes'
    app.recipes.service.class: App\ExternalApi\Recipes\Service\RecipesService
    app.morph.baseurl: 'https://morph.api.bbci.co.uk'
    app.LxPromo.service.lxpromo.class: App\ExternalApi\LxPromo\Service\LxPromoService
    app.riddle.service.riddle.class: App\ExternalApi\Riddle\Service\RiddleService
    app.sounds_nav.baseurl: 'https://sounds-nav.api.bbci.co.uk/json?contentTypeLabel=schedule'
    app.sounds_nav.service.class: App\ExternalApi\SoundsNav\Service\SoundsNavService
    app.tupac.baseurl: 'https://music-tupac.api.bbc.co.uk'
    app.tupac.service.class: App\ExternalApi\Tupac\Service\TupacService
    app.services.smallprox.endpoint: 'https://smallprox.vj.tools.bbc.co.uk'

    # External JS
    app.vote.accountwrapperurl: 'https://account-wrapper.files.bbci.co.uk/vote-wrapper.min.js'

    #Dials
    app.cosmos.dials.path: '/etc/cosmos-dials/dials.json'

    # How long to cache items in a stale-while-revalidate state for things using
    # the resilient redis cache layer
    app.cache.resilient_cache_time: 21600

    app.logos.version_strategy.class: App\Branding\LogoVersionStrategy
    app.logos.base_url: https://programmes.files.bbci.co.uk/programmes-frontend
    # How long to cache the dynamic S3 asset manifest. also see services_dev
    app.logos.cache.ttl: 600

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # List of services to be autowired, please be conservative
    # note: This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/{Branding,Cosmos,Translate,Twig,Ds2013/Factory,DsAmen/Factory,DsShared/Factory}'

    App\ExternalApi\:
        resource: '../src/ExternalApi/*/{Mapper,Factory,Helpers,Service}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        exclude: '../src/Controller/Helpers'
        tags: ['controller.service_arguments']

    # Helpers separate from controllers to prevent method autowiring
    App\Controller\Helpers\:
        resource: '../src/Controller/Helpers'

    ### Begin the services!

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Branding\LogoVersionStrategy:
        class: '%app.logos.version_strategy.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@cache.logos_cache'
            - '@logger'
            - '%app.logos.base_url%'
            - 'rev-logos.$env$.json'
            - '@App\ValueObject\CosmosInfo'
            - '%app.logos.cache.ttl%'

    App\DsShared\Helpers\TitleLogicHelper:
        factory: 'App\DsShared\Factory\HelperFactory:getTitleLogicHelper'

    App\DsShared\Helpers\LiveBroadcastHelper:
        factory: 'App\DsShared\Factory\HelperFactory:getLiveBroadcastHelper'

    App\DsShared\Helpers\PlayTranslationsHelper:
        factory: 'App\DsShared\Factory\HelperFactory:getPlayTranslationsHelper'

    App\DsShared\Helpers\SmpPlaylistHelper:
        factory: 'App\DsShared\Factory\HelperFactory:getSmpPlaylistHelper'

    App\DsShared\Helpers\StreamableHelper:
        factory: 'App\DsShared\Factory\HelperFactory:getStreamUrlHelper'

    App\ExternalApi\Isite\Mapper\ArticleMapper:
        factory: 'App\ExternalApi\Isite\Mapper\MapperFactory:createArticleMapper'

    App\ExternalApi\Isite\Mapper\ProfileMapper:
        factory: 'App\ExternalApi\Isite\Mapper\MapperFactory:createProfileMapper'

    App\ExternalApi\XmlParser\XmlParser: ~

    App\Cosmos\Dials:
        arguments:
            $path: '%app.cosmos.dials.path%'

    # Event Subscribers
    App\EventSubscriber\FindByPidRouterSubscriber: ~
    App\EventSubscriber\ResponseSubscriber: ~
    App\EventSubscriber\CacheFlushSubscriber: ~
    App\EventSubscriber\MonitoringSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\ValueObject\CosmosInfo:
        arguments: ['%cosmos_component_release%', '%cosmos_environment%']

    App\Redis\RedisClusterFactory: ~

    App\Controller\ExceptionController:
        public: true
        arguments:
            $debug: '%kernel.debug%'

    ### Argument Value Resolvers

    App\ArgumentResolver\ContextEntityByPidValueResolver:
        tags: [{name: 'controller.argument_value_resolver', priority: 0 }]

    # This needs to be triggered before the RequestAttributeValueResolver,
    # which has a priority of 100
    App\ArgumentResolver\IdentifierValueResolver:
        tags: [{name: 'controller.argument_value_resolver', priority: 125 }]

    App\ArgumentResolver\CategoryByUrlKeyValueResolver:
        tags: [{name: 'controller.argument_value_resolver', priority: 0 }]

    ### Caches

    cache.null_provider:
        class: Symfony\Component\Cache\Adapter\NullAdapter

    cache.logos_cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - 'logos'
            - '%app.logos.cache.ttl%'
            - '%kernel.cache_dir%'

    # we need an instance of RedisCluster, default Redis class doesn't support cluster mode.
    # RedisCluster class support most Redis operations
    cache.default_redis_provider:
        factory: 'App\Redis\RedisClusterFactory:createRedisCluster'
        class: App\Redis\RedisClusterFactory
        arguments:
            - ['%redis_endpoint%']
            - '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'cache' }

    ### iSite Feed Handlers
    isite.feed_response_handler.article:
        class: App\ExternalApi\Isite\IsiteFeedResponseHandler
        arguments:
            $mapper: '@App\ExternalApi\Isite\Mapper\ArticleMapper'

    isite.feed_response_handler.profile:
        class: App\ExternalApi\Isite\IsiteFeedResponseHandler
        arguments:
            $mapper: '@App\ExternalApi\Isite\Mapper\ProfileMapper'


    ### Http Clients

    BBC\BrandingClient\OrbitClient:
        class: '%app.orbit_client.class%'
        arguments:
            - '@logger'
            - '@csa_guzzle.client.default'
            - '@BBC\ProgrammesCachingLibrary\CacheWithResilience'
            - env: '%app.feed_env.orbit%'
              cacheKeyPrefix: 'programmes-frontend.%cosmos_component_release%.orbit'
              mustache: { cache: '%kernel.cache_dir%/mustache' }

    BBC\BrandingClient\BrandingClient:
        class: '%app.branding_client.class%'
        arguments:
            - '@logger'
            - '@csa_guzzle.client.default'
            - '@BBC\ProgrammesCachingLibrary\CacheWithResilience'
            - env: '%app.feed_env.branding%'
              cacheKeyPrefix: 'programmes-frontend.%cosmos_component_release%.branding'

    BBC\ProgrammesMorphLibrary\MorphClient:
        class: '%app.morph_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@BBC\ProgrammesCachingLibrary\Cache'
            - '@logger'
            - '%app.morph.baseurl%'

    ### Translations

    identity_translator:
        class: App\Translate\Translator

    translation.loader.po:
        class: App\Translate\PoFileLoaderExceptItActuallyWorks
        tags:
            - name: translation.loader
              alias: po

    ### Monitoring

    App\Metrics\MetricsManager: ~

    App\Metrics\MetricsMiddleware:
        tags:
            - { name: 'csa_guzzle.middleware', alias: 'metrics_middleware', pritority: 90 }

    App\ExternalApi\CircuitBreaker\CircuitBreakerMiddleware:
        tags:
            - { name: 'csa_guzzle.middleware', alias: 'circuit_breaker_middleware', pritority: 100 }

    RMP\CloudwatchMonitoring\MonitoringHandler:
        arguments:
            $namespace: 'frontend'
            $env: '%cosmos_environment%'

    Aws\CloudWatch\CloudWatchClient:
        arguments:
            - region: '%aws_s3_region%'
              version: '2010-08-01'
              http:
                timeout: '%frontend.aws.http_timeout%'
                connect_timeout: '%frontend.aws.http_connect_timeout%'


    App\Metrics\Backend\MetricBackendInterface:
        class: '%app.metric_backend.class%'

    App\Metrics\Cache\MetricCacheInterface:
        class: "%app.metric_cache.class%"

    ## Caching Library

    BBC\ProgrammesCachingLibrary\CacheInterface:
        alias: BBC\ProgrammesCachingLibrary\Cache

    BBC\ProgrammesCachingLibrary\CacheWithResilience:
        arguments:
            - '@logger'
            - '@cache.programmes'
            - 'programmes-frontend.%cosmos_component_release%'
            - '%app.cache.resilient_cache_time%'
            - []
            - ['Doctrine\DBAL\Exception\DriverException']

    BBC\ProgrammesCachingLibrary\Cache:
        arguments: ['@cache.programmes', 'programmes-frontend.%cosmos_component_release%']

    ### Programmes Service

    BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\MapperFactory: ~

    BBC\ProgrammesPagesService\Service\ServiceFactory:
        public: true
        arguments:
            $cache: '@BBC\ProgrammesCachingLibrary\CacheWithResilience'

    BBC\ProgrammesPagesService\Service\SegmentsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getSegmentsService']

    BBC\ProgrammesPagesService\Service\SegmentEventsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getSegmentEventsService']

    BBC\ProgrammesPagesService\Service\AtozTitlesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getAtozTitlesService']

    BBC\ProgrammesPagesService\Service\CategoriesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getCategoriesService']

    BBC\ProgrammesPagesService\Service\BroadcastsService:
        public: true
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getBroadcastsService']

    BBC\ProgrammesPagesService\Service\CollapsedBroadcastsService:
        public: true
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getCollapsedBroadcastsService']

    BBC\ProgrammesPagesService\Service\ContributorsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getContributorsService']

    BBC\ProgrammesPagesService\Service\ContributionsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getContributionsService']

    BBC\ProgrammesPagesService\Service\CoreEntitiesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getCoreEntitiesService']

    BBC\ProgrammesPagesService\Service\GroupsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getGroupsService']

    BBC\ProgrammesPagesService\Service\ImagesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getImagesService']

    BBC\ProgrammesPagesService\Service\NetworksService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getNetworksService']

    BBC\ProgrammesPagesService\Service\PodcastsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getPodcastsService']

    BBC\ProgrammesPagesService\Service\ProgrammesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getProgrammesService']

    BBC\ProgrammesPagesService\Service\ProgrammesAggregationService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getProgrammesAggregationService']

    BBC\ProgrammesPagesService\Service\PromotionsService:
         factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getPromotionsService']

    BBC\ProgrammesPagesService\Service\RelatedLinksService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getRelatedLinksService']

    BBC\ProgrammesPagesService\Service\ServicesService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getServicesService']

    BBC\ProgrammesPagesService\Service\VersionsService:
        factory: ['@BBC\ProgrammesPagesService\Service\ServiceFactory', 'getVersionsService']

    ### Cache null adapter for the status controller
    null_cache:
        class: 'BBC\ProgrammesCachingLibrary\Cache'
        arguments:
            - '@cache.null_provider'
            - 'nullcache'

    null_cache_service_factory:
        class: BBC\ProgrammesPagesService\Service\ServiceFactory
        public: true
        arguments:
            $cache: '@null_cache'

    App\Controller\StatusController:
        public: true
        arguments:
            - '@null_cache_service_factory'

    # API services

    App\ExternalApi\Ada\Service\AdaClassService:
        class: '%app.ada.class_service.class%'
        arguments:
            $baseUrl: '%app.ada.baseurl%'

    App\ExternalApi\Ada\Service\AdaProgrammeService:
        class: '%app.ada.programme_service.class%'
        arguments:
            $baseUrl: '%app.ada.baseurl%'

    App\ExternalApi\Electron\Service\ElectronService:
        class: '%app.electron.service.class%'
        arguments:
            $baseUrl: '%app.electron.baseurl%'

    App\ExternalApi\Isite\Service\ArticleService:
        class: '%app.isite.article_service.class%'
        arguments:
            $baseUrl: '%app.isite.baseurl%'
            $responseHandler: '@isite.feed_response_handler.article'

    App\ExternalApi\Isite\Service\ProfileService:
        class: '%app.isite.profile_service.class%'
        arguments:
            $baseUrl: '%app.isite.baseurl%'
            $responseHandler: '@isite.feed_response_handler.profile'

    App\ExternalApi\Recipes\Service\RecipesService:
        class: '%app.recipes.service.class%'
        arguments:
            $baseUrl: '%app.recipes.baseurl%'

    App\ExternalApi\LxPromo\Service\LxPromoService:
        class: '%app.LxPromo.service.lxpromo.class%'
        arguments:
            $lxPromoEnv: '%app.feed_env.morph.lxpromo%'

    App\ExternalApi\Riddle\Service\RiddleService:
        class: '%app.riddle.service.riddle.class%'
        arguments:
            $riddleEnv: '%app.feed_env.morph.riddle%'

    App\ExternalApi\SoundsNav\Service\SoundsNavService:
        class: '%app.sounds_nav.service.class%'
        arguments:
            $url: '%app.sounds_nav.baseurl%'

    App\ExternalApi\Tupac\Service\TupacService:
        class: '%app.tupac.service.class%'
        arguments:
            $baseUrl: '%app.tupac.baseurl%'

    App\ExternalApi\IdtQuiz\Service\IdtQuizService:
        class: '%app.idtquiz.service.class%'
        arguments:
            $clientFactory: '@App\ExternalApi\Client\Factory\HttpApiClientFactory'
            $smallproxEndpoint: '%app.services.smallprox.endpoint%'

