parameters:
    app.metric_backend.class: App\Metrics\Backend\LogMetricBackend
    app.feed_env.branding: 'test'

    app.vote.accountwrapperurl: 'https://account-wrapper.test.files.bbci.co.uk/vote-wrapper.min.js'

    app.cosmos.dials.path: '../dials.json'
    app.logos.cache.ttl: 20

services:
    BBC\ProgrammesCachingLibrary\CacheWithResilience:
        arguments:
            - '@logger'
            - '@cache.programmes'
            - 'programmes-frontend.%cosmos_component_release%'
            - '%app.cache.resilient_cache_time%'
            - []
            - [] # Not adding any exception here so we can see the errors in Dev
